# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./frontend /app

# Install Node.js dependencies
RUN npm install

# Build the React app
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Define the command to run your application
CMD ["npm", "start"]
